name: wechat_assets_picker
description: An audio/video/image picker in pure Dart which is the same with WeChat, support multi picking.
version: 7.0.5

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.8.0'

dependencies:
  flutter:
    sdk: flutter

  extended_image:
    git:
      url: git@github.com:chaudharydeepanshu/extended_image.git
      ref: master
  meta: ^1.7.0
  photo_manager: ^2.0.2
  provider: ^6.0.2
  video_player: ^2.2.14
